# Generated by Django 3.1.5 on 2021-01-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0002_auto_20210118_2135'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sem',
            table='Sem',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
