# Generated by Django 3.1.5 on 2021-01-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0003_auto_20210118_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem',
            name='sem',
            field=models.IntegerField(default=0),
        ),
    ]
