# Generated by Django 3.1.5 on 2021-01-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0004_sem_sem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sem_id',
            new_name='sem',
        ),
        migrations.AddField(
            model_name='student',
            name='branch_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentdata.branch'),
        ),
    ]
