# Generated by Django 3.1.5 on 2021-01-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0007_auto_20210122_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200, null=True)),
                ('total_marks', models.IntegerField(max_length=10, null=True)),
                ('reg_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentdata.studentreg2')),
            ],
            options={
                'db_table': 'Marks',
            },
        ),
    ]
