# Generated by Django 3.1.5 on 2021-01-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0008_totalmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalmarks',
            name='subject_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
